GitHub
GitHub Action:

place the following code at the root of your GitHub repo in:

.github/workflows/linter.yaml

WARNING!
Never, never, never add this file in or touch it in Repl.it. ONLY add it in from GitHub.
(If you do touch it in Repl.it, it will most likely lock your Repl and you will have to start all over again!)
###############################################

# Run GitHub's Super Linter against code base #

###############################################



name: linter



on: push



jobs:

  run-linters:

    name: Linters

    runs-on: ubuntu-latest



    steps:

      - name: Check out Git repository

        uses: actions/checkout@master

        

      - name: GitHub Super-Linter

        uses: github/super-linter@master

        env:

          VALIDATE_ALL_CODEBASE: true

          DEFAULT_BRANCH: master

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
